spring:
  application:
    name: discovery-service

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
  server:
    eviction-interval-timer-in-ms: 60000
